[2020-07-01 16:27:18,349] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_data_dag.upload_data_mysql_task 2020-07-01T10:53:27.593877+00:00 [queued]>
[2020-07-01 16:27:18,357] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_data_dag.upload_data_mysql_task 2020-07-01T10:53:27.593877+00:00 [queued]>
[2020-07-01 16:27:18,357] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-01 16:27:18,357] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-07-01 16:27:18,357] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-01 16:27:18,364] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): upload_data_mysql_task> on 2020-07-01T10:53:27.593877+00:00
[2020-07-01 16:27:18,366] {standard_task_runner.py:53} INFO - Started process 50815 to run task
[2020-07-01 16:27:18,408] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_data_dag.upload_data_mysql_task 2020-07-01T10:53:27.593877+00:00 [running]> localhost.localdomain
[2020-07-01 16:27:29,752] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-07-01 16:27:29,755] {taskinstance.py:1052} INFO - Marking task as SUCCESS.dag_id=covid_data_dag, task_id=upload_data_mysql_task, execution_date=20200701T105327, start_date=20200701T105718, end_date=20200701T105729
[2020-07-01 16:27:33,371] {logging_mixin.py:112} INFO - [2020-07-01 16:27:33,370] {local_task_job.py:103} INFO - Task exited with return code 0
