[2020-07-03 17:40:58,039] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_data_dag.connect_mysql_task 2020-07-03T12:07:57.655844+00:00 [queued]>
[2020-07-03 17:40:58,046] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_data_dag.connect_mysql_task 2020-07-03T12:07:57.655844+00:00 [queued]>
[2020-07-03 17:40:58,046] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-03 17:40:58,046] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-07-03 17:40:58,046] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-03 17:40:58,055] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): connect_mysql_task> on 2020-07-03T12:07:57.655844+00:00
[2020-07-03 17:40:58,057] {standard_task_runner.py:53} INFO - Started process 71866 to run task
[2020-07-03 17:40:58,099] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_data_dag.connect_mysql_task 2020-07-03T12:07:57.655844+00:00 [running]> localhost.localdomain
[2020-07-03 17:40:58,132] {logging_mixin.py:112} INFO - Connected to MySQL
[2020-07-03 17:40:58,133] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-07-03 17:40:58,143] {taskinstance.py:1052} INFO - Marking task as SUCCESS.dag_id=covid_data_dag, task_id=connect_mysql_task, execution_date=20200703T120757, start_date=20200703T121058, end_date=20200703T121058
[2020-07-03 17:41:08,029] {logging_mixin.py:112} INFO - [2020-07-03 17:41:08,028] {local_task_job.py:103} INFO - Task exited with return code 0
